<?xml version="1.0"?>
<package format="3">
  <name>taskspace_controllers</name>
  <version>0.1.1</version>
  <description>A base package for task-space controllers</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>Apache2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>urdf</depend>
  <depend>kdl_parser</depend>
  <depend>pluginlib</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>
  <depend>joint_limits</depend>
  <depend>generate_parameter_library</depend>
  <depend>realtime_tools</depend>
  <depend>taskspace_control_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <controller_interface plugin="${prefix}/taskspace_controller_plugins.xml"/>
  </export>
</package>
