<?xml version="1.0"?>
<package format="3">
  <name>axially_symmetric_controllers</name>
  <version>0.1.0</version>
  <description>The axially_symmetric_controllers package</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>Apache2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>urdf</depend>
  <depend>kdl_parser</depend>
  <depend>pluginlib</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>
  <depend>generate_parameter_library</depend>
  <depend>realtime_tools</depend>
  <depend>taskspace_control_msgs</depend>
  <depend>taskspace_controllers</depend>
  <depend>task_priority_controllers</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <controller_interface plugin="${prefix}/axially_symmetric_controller_plugins.xml"/>
  </export>
</package>
