// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "task_priority_controllers/pose_controller.hpp"

// auto-generated by generate_parameter_library
#include "axially_symmetric_controllers/axially_symmetric_controller_parameters.hpp"

namespace axially_symmetric_controllers
{

class AxiallySymmetricControllerBase
  : public task_priority_controllers::PoseController
{
public:
  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

protected:
  std::shared_ptr<axially_symmetric_controller::ParamListener>
      as_param_listener_;
  axially_symmetric_controller::Params as_params_;

  // aiming axes
  ctrl::Vector3D tool_frame_axis_;
  ctrl::Vector3D setpoint_frame_axis_;
};

}  // namespace axially_symmetric_controllers
