# 7R robot simulation hardware
generic_hw_control_loop:
  loop_hz: 1000
  cycle_time_error_threshold: 0.01

hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  sim_control_mode: 0  # 0: position, 1: velocity

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# 7R robot controllers
pose_controller:
  type: taskspace_controllers/PoseController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  base_link: base_link
  eef_link: tool0

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

task_priority_controller:
  type: task_priority_controllers/PoseController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  base_link: base_link
  eef_link: tool0

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

  objective_type: maximize_manipulability
  rr_objective:
    k_manip: 10.0

as_nullspace_controller:
  type: axially_symmetric_controllers/NullspaceController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  base_link: base_link
  eef_link: tool0

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

  objective_type: maximize_manipulability
  rr_objective:
    k_manip: 10.0

as_twist_decomposition_controller:
  type: axially_symmetric_controllers/TwistDecompositionController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  base_link: base_link
  eef_link: tool0

  k_position: 10.0
  k_orient: 10.0

  setpoint_topic: setpoint

  objective_type: maximize_manipulability
  rr_objective:
    k_manip: 10.0

joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
