// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <taskspace_controllers/taskspace_controller_base.hpp>
#include <taskspace_controllers/setpoint.hpp>

#include <kdl/chainjnttojacsolver.hpp>

#include <taskspace_control_msgs/msg/pose_twist_setpoint.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp>
#include <realtime_tools/realtime_buffer.hpp>

// auto-generated by generate_parameter_library
#include <taskspace_controllers/pose_controller_parameters.hpp>

namespace taskspace_controllers
{

class PoseController : public virtual TaskspaceControllerBase
{
public:
  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

protected:
  using Setpoint = taskspace_controllers::PoseTwistSetpoint;

  // Parameters from ROS for joint_trajectory_controller
  std::shared_ptr<pose_controller::ParamListener> pose_param_listener_;
  pose_controller::Params pose_params_;

  // -- Kinematics --
  std::unique_ptr<KDL::ChainJntToJacSolver> robot_jacobian_solver_;

  // -- Setpoint subscription --
  realtime_tools::RealtimeBuffer<Setpoint> setpoint_buffer_;
  rclcpp::Subscription<taskspace_control_msgs::msg::PoseTwistSetpoint>::
      SharedPtr setpoint_subscriber_;

  void setpointCallback(
      const taskspace_control_msgs::msg::PoseTwistSetpoint::SharedPtr msg);
};

}  // namespace taskspace_controllers
