// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <kdl/chain.hpp>
#include <kdl/jntarray.hpp>
#include <kdl/jntarrayvel.hpp>
#include <kdl/chainfksolverpos_recursive.hpp>

#include "realtime_tools/realtime_publisher.hpp"
#include "taskspace_controllers/utility.hpp"
#include "taskspace_control_msgs/msg/taskspace_control_diagnostic.hpp"
#include "taskspace_control_msgs/srv/query_pose.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"
#include "controller_interface/controller_interface.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "joint_limits/joint_limits.hpp"

#include "ros2_version_config.h"

// auto-generated by generate_parameter_library
#include "taskspace_controllers/taskspace_controller_base_parameters.hpp"

namespace taskspace_controllers
{

class TaskspaceControllerBase : public controller_interface::ControllerInterface
{
public:
  virtual controller_interface::InterfaceConfiguration
  command_interface_configuration() const override;

  virtual controller_interface::InterfaceConfiguration
  state_interface_configuration() const override;

  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

  virtual controller_interface::CallbackReturn
  on_shutdown(const rclcpp_lifecycle::State& previous_state) override;

protected:
  // Hardware interface methods
  void read_state_from_hardware(KDL::JntArrayVel& state);
  void stop_motion();
  void write_command(const KDL::JntArrayVel& cmd);

  // Utility functions
  bool check_manipulability(const KDL::Jacobian& jac);

  // Callbacks
  using QueryPose = taskspace_control_msgs::srv::QueryPose;
  virtual bool queryPoseServiceCb(const std::shared_ptr<QueryPose::Request> req,
                                  std::shared_ptr<QueryPose::Response> resp);

  std::shared_ptr<taskspace_controller_base::ParamListener> param_listener_;
  taskspace_controller_base::Params params_;

  const std::vector<std::string> allowed_interface_types_ = {
    hardware_interface::HW_IF_POSITION,
    hardware_interface::HW_IF_VELOCITY,
  };

  // Diagnostic publishing helper
  void publish_state_diagnostic(const rclcpp::Time& time,
                                const KDL::JntArrayVel& joint_cmd,
                                const KDL::JntArrayVel& joint_state,
                                const KDL::JntArrayVel& state_error,
                                const ctrl::Pose& sp_pose,
                                const ctrl::Pose& pose,
                                const ctrl::Vector3D& trans_error,
                                const ctrl::Vector3D& orient_error);

  bool has_position_command_interface_ = false;
  bool has_velocity_command_interface_ = false;
  bool has_position_state_interface_ = false;
  bool has_velocity_state_interface_ = false;
  size_t position_state_interface_index_ = 0;
  size_t velocity_state_interface_index_ = 0;

  // Controller parameters
  std::vector<std::string> joint_names_;
  unsigned int n_joints_ = 0;
  std::string base_link_, eef_link_;

  // Kinematics
  KDL::Chain robot_chain_;
  std::vector<joint_limits::JointLimits> joint_limits_;
  std::unique_ptr<KDL::ChainFkSolverPos_recursive> robot_fk_solver_;

  // State tracking
  KDL::JntArrayVel joint_state_;
  KDL::JntArrayVel last_commanded_;
  KDL::JntArrayVel last_reference_;

  // Services
  rclcpp::Service<QueryPose>::SharedPtr query_pose_service_;

  // Diagnostic
  std::unique_ptr<realtime_tools::RealtimePublisher<
      taskspace_control_msgs::msg::TaskspaceControlDiagnostic>>
      rt_state_pub_;
  std::shared_ptr<
      rclcpp::Publisher<taskspace_control_msgs::msg::TaskspaceControlDiagnostic>>
      state_pub_;
  taskspace_control_msgs::msg::TaskspaceControlDiagnostic diagnostic_msg_;
};

}  // namespace taskspace_controllers
