// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <taskspace_controllers/utility.hpp>

#include <kdl/chain.hpp>
#include <kdl/jntarray.hpp>
#include <kdl/jntarrayvel.hpp>
#include <kdl/chainfksolverpos_recursive.hpp>

#include <rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp>
#include <taskspace_control_msgs/srv/query_pose.hpp>
#include <trajectory_msgs/msg/joint_trajectory_point.hpp>
#include <controller_interface/controller_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>

#include "ros2_version_config.h"

// auto-generated by generate_parameter_library
#include <taskspace_controllers/taskspace_controller_base_parameters.hpp>

namespace taskspace_controllers
{

class TaskspaceControllerBase : public controller_interface::ControllerInterface
{
public:
  virtual controller_interface::InterfaceConfiguration
  command_interface_configuration() const override;

  virtual controller_interface::InterfaceConfiguration
  state_interface_configuration() const override;

  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

protected:
  const std::vector<std::string> allowed_interface_types_ = {
    hardware_interface::HW_IF_POSITION,
    hardware_interface::HW_IF_VELOCITY,
  };

  void read_state_from_hardware(KDL::JntArrayVel& state);
  void write_command(const KDL::JntArrayVel& cmd);

  KDL::JntArrayVel create_kdl_state(const ctrl::VectorND& q,
                                    const ctrl::VectorND& qdot);

  std::shared_ptr<taskspace_controller_base::ParamListener> param_listener_;
  taskspace_controller_base::Params params_;

  template <typename T>
  using InterfaceReferences =
      std::vector<std::vector<std::reference_wrapper<T>>>;

  InterfaceReferences<hardware_interface::LoanedCommandInterface>
      joint_command_handles_;
  InterfaceReferences<hardware_interface::LoanedStateInterface>
      joint_state_handles_;

  bool has_position_command_interface_ = false;
  bool has_velocity_command_interface_ = false;

  unsigned int n_joints_ = 0;
  std::string base_link_, eef_link_;

  // kinematics
  KDL::Chain robot_chain_;
  KDL::JntArray upper_pos_limits_;
  KDL::JntArray lower_pos_limits_;
  std::unique_ptr<KDL::ChainFkSolverPos_recursive> robot_fk_solver_;

  // state feedback
  KDL::JntArrayVel last_commanded_;
  KDL::JntArrayVel last_reference_;

  // control loop data
  KDL::JntArrayVel joint_state_;

  using QueryPose = taskspace_control_msgs::srv::QueryPose;
  rclcpp::Service<QueryPose>::SharedPtr query_pose_service_;

  virtual bool queryPoseServiceCb(const std::shared_ptr<QueryPose::Request> req,
                                  std::shared_ptr<QueryPose::Response> resp);

private:
  bool
  contains_interface_type(const std::vector<std::string>& interface_type_list,
                          const std::string& interface_type);
};

}  // namespace taskspace_controllers
